/********************************************************************
* mySpyDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error mySpyDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablemySpyDict();
extern void G__cpp_setup_inheritancemySpyDict();
extern void G__cpp_setup_typetablemySpyDict();
extern void G__cpp_setup_memvarmySpyDict();
extern void G__cpp_setup_globalmySpyDict();
extern void G__cpp_setup_memfuncmySpyDict();
extern void G__cpp_setup_funcmySpyDict();
extern void G__set_cpp_environmentmySpyDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "mySpy.h"
#include "ATrack.h"
#include "AEvent.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__mySpyDictLN_TClass;
extern G__linked_taginfo G__mySpyDictLN_TBuffer;
extern G__linked_taginfo G__mySpyDictLN_TMemberInspector;
extern G__linked_taginfo G__mySpyDictLN_TObject;
extern G__linked_taginfo G__mySpyDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__mySpyDictLN_basic_ofstreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__mySpyDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__mySpyDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__mySpyDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__mySpyDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__mySpyDictLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__mySpyDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__mySpyDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__mySpyDictLN_TGLayoutHints;
extern G__linked_taginfo G__mySpyDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__mySpyDictLN_TGTextButton;
extern G__linked_taginfo G__mySpyDictLN_TGHorizontalFrame;
extern G__linked_taginfo G__mySpyDictLN_TGMainFrame;
extern G__linked_taginfo G__mySpyDictLN_TGButton;
extern G__linked_taginfo G__mySpyDictLN_TRootEmbeddedCanvas;
extern G__linked_taginfo G__mySpyDictLN_TSocket;
extern G__linked_taginfo G__mySpyDictLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__mySpyDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__mySpyDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR;
extern G__linked_taginfo G__mySpyDictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__mySpyDictLN_ATrack;
extern G__linked_taginfo G__mySpyDictLN_AEvent;
extern G__linked_taginfo G__mySpyDictLN_vectorlEATrackmUcOallocatorlEATrackmUgRsPgR;
extern G__linked_taginfo G__mySpyDictLN_vectorlEATrackmUcOallocatorlEATrackmUgRsPgRcLcLiterator;
extern G__linked_taginfo G__mySpyDictLN_reverse_iteratorlEvectorlEATrackmUcOallocatorlEATrackmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__mySpyDictLN_TH1F;
extern G__linked_taginfo G__mySpyDictLN_TGraph;
extern G__linked_taginfo G__mySpyDictLN_TMultiGraph;
extern G__linked_taginfo G__mySpyDictLN_mySpy;

/* STUB derived class for protected member access */
